# Generated by Django 6.1.1 on 2026-10-06 13:57

from django.db import migrations, models

def convert_null_to_empty_string(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')

    Car.objects.filter(plate__isnull=True).update(plate='')

    Car.objects.filter(plate='None').update(plate='')
    Car.objects.filter(plate='null').update(plate='')

class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_plate'),
    ]

    operations = [
        migrations.RunPython(convert_null_to_empty_string),

        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
